/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceLogsRouteImport } from './routes/voice-logs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QSlugRouteImport } from './routes/q.$slug'
import { Route as OnboardingIdRouteImport } from './routes/onboarding.$id'

const VoiceLogsRoute = VoiceLogsRouteImport.update({
  id: '/voice-logs',
  path: '/voice-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QSlugRoute = QSlugRouteImport.update({
  id: '/q/$slug',
  path: '/q/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIdRoute = OnboardingIdRouteImport.update({
  id: '/onboarding/$id',
  path: '/onboarding/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/voice-logs': typeof VoiceLogsRoute
  '/onboarding/$id': typeof OnboardingIdRoute
  '/q/$slug': typeof QSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/voice-logs': typeof VoiceLogsRoute
  '/onboarding/$id': typeof OnboardingIdRoute
  '/q/$slug': typeof QSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/voice-logs': typeof VoiceLogsRoute
  '/onboarding/$id': typeof OnboardingIdRoute
  '/q/$slug': typeof QSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/meetings'
    | '/settings'
    | '/voice-logs'
    | '/onboarding/$id'
    | '/q/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/meetings'
    | '/settings'
    | '/voice-logs'
    | '/onboarding/$id'
    | '/q/$slug'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/meetings'
    | '/settings'
    | '/voice-logs'
    | '/onboarding/$id'
    | '/q/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  MeetingsRoute: typeof MeetingsRoute
  SettingsRoute: typeof SettingsRoute
  VoiceLogsRoute: typeof VoiceLogsRoute
  OnboardingIdRoute: typeof OnboardingIdRoute
  QSlugRoute: typeof QSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-logs': {
      id: '/voice-logs'
      path: '/voice-logs'
      fullPath: '/voice-logs'
      preLoaderRoute: typeof VoiceLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$slug': {
      id: '/q/$slug'
      path: '/q/$slug'
      fullPath: '/q/$slug'
      preLoaderRoute: typeof QSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$id': {
      id: '/onboarding/$id'
      path: '/onboarding/$id'
      fullPath: '/onboarding/$id'
      preLoaderRoute: typeof OnboardingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  MeetingsRoute: MeetingsRoute,
  SettingsRoute: SettingsRoute,
  VoiceLogsRoute: VoiceLogsRoute,
  OnboardingIdRoute: OnboardingIdRoute,
  QSlugRoute: QSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
